(ql:quickload :str)
(ql:quickload :split-sequence)
(use-package :split-sequence)
(ql:quickload :arrows)
(use-package :arrows)
(-<>> (uiop:read-file-string #P"input")
      str:lines
      (split-sequence-if #'str:blank?)
      (mapcar (lambda (l)
		(apply #'+ (mapcar #'parse-integer l))))
      (sort <> #'>)
      (subseq <> 0 3)
      print)
